### ISSUE TITLE
ld: framework not found FirebaseAnalytics

### ISSUE THREAD

**Issue by LuisRodriguezLD** [fuse-compound/Fuse.Firebase#29] opened 2017-01-12 17:28 UTC
I am getting the following error while building in Xcode
`ld: framework not found FirebaseAnalytics clang: error: linker command failed with exit code 1 (use -v to see invocation) `

I am using Fuse .32, has something changed? 
I remember being able to get it working.

**Comment by jesusmartinoza** [comment] 2017-01-12 21:29
+1. I can't even download the pods
 `$ [!] The Podfile does not contain any dependencies.`

**Comment by changalberto** [comment] 2017-01-14 23:45
@LuisRodriguezLD Yes, definitely something in version 0.3.2.0 changed that affects it. I rolled back to 0.31.2 and it all works fine now.

@cbaggers Any idea when you'll have time to make and update?

**Comment by cbaggers** [comment] 2017-01-19 15:36
grr Testing with latest internal code seems to work fine..that wasnt very illuminating. I'll install `0.32.0` and have another go

**Comment by cbaggers** [comment] 2017-01-20 10:01
Ahah, yeah I get the same error with version 0.32. It sounds like it's fixed internally then. But the question of why this happened is still there.

When building with 0.32 I got.

```
[!] Please close any current Xcode sessions and use `AuthExample.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 7 dependencies from the Podfile and 16 total pods installed.

[!] The `AuthExample [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-AuthExample/Pods-AuthExample.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `AuthExample [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-AuthExample/Pods-AuthExample.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

The `Please close any current Xcode` one is perfectly normal for cocoapods, so no worries there.
However the next 2 warnings are likely the cause of the problem. Very strange. I'll go see what git says we have been changing recently

**Comment by cbaggers** [comment] 2017-01-20 10:10
AHAH! we found it. The best news is you don't have to do anything to fix it except use the next release (when it's out).

The issue was that we had this section in the project.pbxproj

**Comment by cbaggers** [comment] 2017-01-20 10:15
AHAH! we found it. The best news is you don't have to do anything to fix it except use the next release (when it's out).

The issue was that we had this section in the `project.pbxproj`

```
#if @(Pbxproj.FrameworkDirectories:IsSet)
                FRAMEWORK_SEARCH_PATHS = (
                    @(Pbxproj.FrameworkDirectories)
                );
#endif
```
So if a library was included during the uno build then the search paths would be set. CocoaPods was fine as usually this was false (and cocoapods runs after the uno build is finished).

However we now always include the jetfire framework (to enable websockets), which means `@(Pbxproj.FrameworkDirectories:IsSet)` was true and so we were overriding the `FRAMEWORK_SEARCH_PATHS` variable.

We noticed this internally (after 0.32 shipped) and changed the above section to 

```
#if @(Pbxproj.FrameworkDirectories:IsSet)
                FRAMEWORK_SEARCH_PATHS = (
                    "$(inherited)",
                    @(Pbxproj.FrameworkDirectories)
                );
#endif
```
That `$(inherited)` bit keeps CocoaPods and Uno playing nice together.

This is in the next release, so now we wait (and use 0.31 until it's out)

Sorry for the inconvenience.

**Comment by cbaggers** [comment] 2017-01-20 10:16
decided to reopen this until the new fuse release ships so others can see the issue

**Comment by changalberto** [comment] 2017-01-20 23:39
@cbaggers Thanks for having look at this and the update!

**Comment by cbaggers** [comment] 2017-04-19 13:28
Closing as has been released for a while. Feel free to reopen if you run into the issue again

**Closed by cbaggers** 2017-04-19 13:28 UTC
